# Generated by Django 6.0.3 on 2026-03-21 08:59

import django.db.models.deletion
import main_app_ticket.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, help_text='Auto-generated: TKT-YYYY-NNNNNN', max_length=30, unique=True, verbose_name='Ticket ID')),
                ('entity_type', models.CharField(choices=[('farmer', 'Farmer'), ('sahayak', 'Sahayak / MPP'), ('transporter', 'Transporter'), ('other', 'Other / General')], max_length=15, verbose_name='Entity Type')),
                ('other_caller_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caller Name')),
                ('other_caller_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Caller Mobile')),
                ('other_caller_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caller Location / Village')),
                ('ticket_type', models.CharField(choices=[('Sahayak Commission', 'Sahayak Commission'), ('FAT/SNF Variation', 'FAT/SNF Variation'), ('Rate Issue', 'Rate Issue'), ('Sahayak Machine Issue', 'Sahayak Machine Issue'), ('Variation Issue', 'Variation Issue'), ('Cattle Feed Issue', 'Cattle Feed Issue'), ('Doctor/Treatment/Medicinal/Vet Type Issue', 'Doctor/Treatment/Vet Issue'), ('Loan Query', 'Loan Query'), ('Cattle Induction Query', 'Cattle Induction Query'), ('Semen Query', 'Semen Query'), ('Sugam App Related Issue', 'Sugam App Related Issue'), ('Kisan App Related Issue', 'Kisan App Related Issue'), ('Number Update', 'Number Update'), ('Account Update', 'Account Update'), ('Others', 'Others')], max_length=60, verbose_name='Ticket Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='open', max_length=15, verbose_name='Status')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Issue Description (English)')),
                ('description_hi', models.TextField(blank=True, null=True, verbose_name='Issue Description (Hindi — auto-translated)')),
                ('expected_resolution_date', models.DateField(blank=True, null=True, verbose_name='Expected Resolution Date')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Escalated')),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='One or more employees responsible for resolving this ticket', related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Created By (Caller)')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Escalated To')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main_app_ticket.farmer', verbose_name='Farmer')),
                ('mpp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main_app_ticket.mpp', verbose_name='Sahayak / MPP')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Ticket Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('comment', 'Comment Added'), ('attachment', 'Attachment Added'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('sms_sent', 'SMS Sent'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description shown in the timeline', null=True)),
                ('old_status', models.CharField(blank=True, choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], max_length=15, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='activity_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To (this event)')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main_app_ticket.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Activity',
                'verbose_name_plural': 'Ticket Activities',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main_app_ticket.models.ticket_attachment_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word Document'), ('other', 'Other')], default='other', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main_app_ticket.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, unique=True, verbose_name='Vendor Code')),
                ('account_group', models.CharField(choices=[('ZFMP', 'ZFMP — Milk Procurement'), ('OTHER', 'Other')], default='ZFMP', max_length=10, verbose_name='Account Group')),
                ('search_term1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Search Term 1')),
                ('search_term2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Search Term 2')),
                ('vendor_name', models.CharField(max_length=200, verbose_name='Vendor / Transporter Name')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='IN', max_length=10, null=True)),
                ('incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW — Ex Works'), ('FOB', 'FOB — Free on Board'), ('CIF', 'CIF — Cost, Insurance & Freight'), ('CPT', 'CPT — Carriage Paid To'), ('DAP', 'DAP — Delivered at Place'), ('DDP', 'DDP — Delivered Duty Paid'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('incoterm_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Incoterm Location')),
                ('bank_account_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank Account Number')),
                ('bank_key', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Key (IFSC)')),
                ('account_holder', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('N', 'NEFT'), ('R', 'RTGS'), ('M', 'IMPS'), ('C', 'Cheque'), ('D', 'Demand Draft'), ('Y', 'Bank Transfer (Y)'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='GST Number')),
                ('msme', models.CharField(blank=True, max_length=30, null=True, verbose_name='MSME Registration')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked in SAP')),
                ('company_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='SAP Company Code')),
                ('gl_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='G/L Account')),
                ('sap_created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='SAP Created By')),
                ('sap_created_on', models.DateField(blank=True, null=True, verbose_name='SAP Created On')),
                ('sap_changed_on', models.DateField(blank=True, null=True, verbose_name='SAP Last Changed On')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transporters', to=settings.AUTH_USER_MODEL, verbose_name='Created By (KSTS)')),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'ordering': ['vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='TicketDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('sahayak', 'Sahayak / MPP'), ('transporter', 'Transporter'), ('other', 'Other / General')], max_length=15, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=60, null=True)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('assignee_ids', models.JSONField(blank=True, default=list, verbose_name='Assignee Employee IDs (JSON list)')),
                ('expected_resolution', models.DateField(blank=True, null=True)),
                ('form_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Full Form Snapshot (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drafted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_drafts', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app_ticket.farmer')),
                ('mpp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app_ticket.mpp')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app_ticket.transporter')),
            ],
            options={
                'verbose_name': 'Ticket Draft',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main_app_ticket.transporter', verbose_name='Transporter'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['vendor_code'], name='main_app_ti_vendor__b87f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['gst_number'], name='main_app_ti_gst_num_8ffac5_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['bank_account_no'], name='main_app_ti_bank_ac_493641_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['city'], name='main_app_ti_city_a6e100_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_id'], name='main_app_ti_ticket__7977df_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='main_app_ti_status_fc6983_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='main_app_ti_priorit_6c8bac_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type'], name='main_app_ti_ticket__c3ed5c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['entity_type'], name='main_app_ti_entity__ec8675_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='main_app_ti_created_5fe00e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['farmer'], name='main_app_ti_farmer__39b132_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['mpp'], name='main_app_ti_mpp_id_24e188_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['transporter'], name='main_app_ti_transpo_41475b_idx'),
        ),
    ]
