# Generated by Django 6.0.3 on 2026-03-23 10:27

import django.db.models.deletion
import main_app_ticket.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_ticket', '0002_ticket_ticketactivity_ticketattachment_transporter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_mobile', models.CharField(max_length=20, verbose_name='Recipient Mobile')),
                ('message_text', models.TextField(verbose_name='Message Text')),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='queued', max_length=15)),
                ('gateway_response', models.TextField(blank=True, help_text='Raw response from the SMS gateway API.', null=True, verbose_name='Gateway Response')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_html', models.TextField(help_text='Rich-text HTML produced by the contenteditable editor.', verbose_name='Comment Body (HTML)')),
                ('body_text', models.TextField(blank=True, help_text='Stripped plain-text version for search and SMS previews.', verbose_name='Comment Body (Plain Text)')),
                ('body_hindi', models.TextField(blank=True, help_text='Google Translate output captured on the frontend before submission.', null=True, verbose_name='Comment Body (Hindi — auto-translated)')),
                ('hindi_fallback', models.BooleanField(default=False, help_text='True when translation was unavailable; body_hindi contains the raw English text.', verbose_name='Hindi Fallback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_internal', models.BooleanField(default=False, help_text='If True, this comment is only visible to employees, not to the caller.', verbose_name='Internal Note')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main_app_ticket.models.comment_attachment_upload_path)),
                ('file_name', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel / CSV'), ('ppt', 'PowerPoint'), ('zip', 'Archive (ZIP / RAR)'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment Attachment',
                'verbose_name_plural': 'Comment Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='caller_mobile',
            field=models.CharField(blank=True, help_text='The mobile number the call was actually received from. May differ from the registered entity contact.', max_length=20, null=True, verbose_name='Actual Caller Mobile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='caller_name',
            field=models.CharField(blank=True, help_text='Name of the person who actually called (e.g. son, wife, driver).', max_length=200, null=True, verbose_name='Actual Caller Name'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='caller_relation',
            field=models.CharField(blank=True, choices=[('Self', 'Self (Member / Owner calling directly)'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Neighbour', 'Neighbour'), ('Other Relative', 'Other Relative'), ('MPP Operator', 'MPP Operator'), ('MPP Owner', 'MPP Owner'), ('MPP Assistant', 'MPP Assistant'), ('Driver', 'Driver'), ('Accountant', 'Accountant'), ('Staff Member', 'Staff Member'), ('Agent', 'Agent'), ('Other', 'Other')], help_text='Relationship of the actual caller to the registered farmer/MPP/transporter.', max_length=30, null=True, verbose_name="Caller's Relation to Entity"),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Why this ticket was escalated.', null=True, verbose_name='Escalation Reason'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last SMS Sent At'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='on_behalf_of',
            field=models.CharField(blank=True, help_text="Used for 'Other' entity type: who the caller is calling on behalf of.", max_length=200, null=True, verbose_name='On Behalf Of'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sms_sent_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total SMS notifications sent for this ticket.', verbose_name='SMS Sent Count'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='new_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='old_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='sms_message_preview',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SMS Message Preview'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='sms_recipient',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Recipient Mobile'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='caller_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='caller_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='caller_relation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='on_behalf_of',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='other_caller_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='other_caller_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketdraft',
            name='other_caller_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='cow_heifer_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Ticket Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('comment', 'Comment Added'), ('attachment', 'Attachment Added'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('pending', 'Marked Pending'), ('closed', 'Closed'), ('sms_sent', 'SMS Sent'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel / CSV'), ('ppt', 'PowerPoint'), ('zip', 'Archive (ZIP / RAR)'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='account_group',
            field=models.CharField(choices=[('ZFMP', 'ZFMP — Milk Procurement'), ('OTHER', 'Other')], default='ZFMP', max_length=10),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='search_term1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='search_term2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_escalated'], name='main_app_ti_is_esca_a47d54_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['resolved_at'], name='main_app_ti_resolve_d8f9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['expected_resolution_date'], name='main_app_ti_expecte_b45692_idx'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='main_app_ticket.ticketactivity', verbose_name='Related Activity Event'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms', to=settings.AUTH_USER_MODEL, verbose_name='Sent By'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='main_app_ticket.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app_ticket.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='comment',
            field=models.ForeignKey(blank=True, help_text="Populated when activity_type is 'comment' or 'attachment'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='main_app_ticket.ticketcomment', verbose_name='Related Comment'),
        ),
        migrations.AddIndex(
            model_name='ticketactivity',
            index=models.Index(fields=['ticket', 'created_at'], name='main_app_ti_ticket__736ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketactivity',
            index=models.Index(fields=['activity_type'], name='main_app_ti_activit_04df65_idx'),
        ),
        migrations.AddField(
            model_name='ticketcommentattachment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main_app_ticket.ticketcomment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='ticketcommentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['ticket', 'sent_at'], name='main_app_ti_ticket__f786b5_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['recipient_mobile'], name='main_app_ti_recipie_dbcd48_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['delivery_status'], name='main_app_ti_deliver_28dfbb_idx'),
        ),
    ]
