# Generated by Django 6.0.3 on 2026-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_ticket', '0003_smslog_ticketcomment_ticketcommentattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mix_dry_no',
            field=models.IntegerField(default=0),
        ),
    ]
