# Generated by Django 6.0.3 on 2026-03-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_ticket', '0004_alter_farmer_mix_dry_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('reopened', 'Reopened')], default='open', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='new_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('reopened', 'Reopened')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='old_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('reopened', 'Reopened')], max_length=15, null=True),
        ),
    ]
