# Generated by Django 6.0.3 on 2026-04-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_ticket', '0005_alter_ticket_status_alter_ticketactivity_new_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Tier-1 Sent At')),
                ('tier1_recipient', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Tier-1 Recipient (Manager)')),
                ('tier2_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Tier-2 Sent At')),
                ('tier2_recipient', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Tier-2 Recipient (C.E.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_notification', to='main_app_ticket.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Escalation Notification',
                'verbose_name_plural': 'Escalation Notifications',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tier1_sent_at'], name='main_app_ti_tier1_s_e8a803_idx'), models.Index(fields=['tier2_sent_at'], name='main_app_ti_tier2_s_c26f54_idx')],
            },
        ),
    ]
